---
title: "Experiment 4: Even More Airline Data"
date: "2023-09-13"
output: html_notebook
---
The experiment continues our class work on flight data.
We will expand our dataset by going to a root source - the Bureau of Transportation

# Packages 

```{r}
library(nycflights13)
library(tidyverse)
library(janitor)
library(here)
```

# Load BOT data
```{r}
thisfile = here("DL_SelectFields_2017.zip")
df2017 = read_csv(thisfile) %>% clean_names()

thisfile = here("DL_SelectFields_2018.zip")
df2018 = read_csv(thisfile) %>% clean_names()

thisfile = here("DL_SelectFields_2019.zip")
df2019 = read_csv(thisfile) %>% clean_names()

thisfile = here("DL_SelectFields_2020.zip")
df2020 = read_csv(thisfile) %>% clean_names()

thisfile = here("DL_SelectFields_2021.zip")
df2021 = read_csv(thisfile) %>% clean_names()

thisfile = here("DL_SelectFields_2022.zip")
df2022 = read_csv(thisfile) %>% clean_names()

thisfile = here("DL_SelectFields_2023.zip")
df2023 = read_csv(thisfile) %>% clean_names()
```

```{r}
dfc = bind_rows(df2017, df2018, df2019, df2020, df2021, df2022, df2023)
```


```{r}

df_lga = dfc %>% filter(passengers > 0, origin == "LGA" | dest == "LGA")

fmonth = ggplot(df_lga, aes(month)) + geom_bar(aes(weight=passengers))

fyear = ggplot(df_lga, aes(year)) + geom_bar(aes(weight=passengers))

fmonth
fyear

```


```{r}

df_lga23 = df_lga %>% filter(year == 2023)

ggplot(df_lga23, aes(month)) + geom_bar(aes(weight=passengers))

```
